### ISSUE TITLE
Calling `RunWithDrivine()` when using `it.each` in a test file causes `TypeError: it.each is not a function`

### ISSUE THREAD

**Issue by NilsMoller** [liberation-data/drivine#114]
The title says it all, but for more detail here is a spec file which shows the issue. The argument for `RunWithDrivine` does not seem to make a difference. Any idea what could be causing this?

```ts
import SLUG_REGEX from "./slug-regex.util";
import { RunWithDrivine } from "@liberation-data/drivine";

RunWithDrivine(); // If this is removed, the tests pass. If this is called, the error shown below is thrown
describe("slug-regex", () => {
  let slugRegex: RegExp;

  beforeEach(async () => {
    slugRegex = new RegExp(SLUG_REGEX);
  });

  it.each([
    "correct",
    "also-correct",
    "this-is-a-valid-slug",
    "c4n-4ls0-c0nt41n-num6er5",
  ])("accepts correct slug string '%s'", async (slugString: string) => {
    // Act
    const result: boolean = slugRegex.test(slugString);

    // Assert
    expect(result).toBeDefined();
    expect(result).toStrictEqual<boolean>(true);
  });
});
```

Error:
```shell
  ● Test suite failed to run

    TypeError: it.each is not a function

       9 |     slugRegex = new RegExp(SLUG_REGEX);
      10 |   });
    > 11 |
         | ^
      12 |   it.each([
      13 |     "correct",
      14 |     "also-correct",

      at utils/slug-regex.util.spec.ts:11:8
      at Object.<anonymous> (utils/slug-regex.util.spec.ts:6:1)
```

**Comment by jasperblues** [comment]
`RunWithDrivine()` is supposed to go at the top of the spec, before jest does anything. 

For a single test, you can use `InDrivineContext.run( () => ` _inside_ the test. 

I appreciate this is a bit confusing.

**Comment by NilsMoller** [comment]
Is this not what I am doing? I am importing the SUT (`SLUG_REGEX` in this case) and the `RunWithDrivine` method, then calling `RunWithDrivine()` and then the first `describe`. Could it have something to do with me using a `globalSetup` file?

**Comment by jasperblues** [comment]
Oh sorry, I thought it was on a nested describe block (was super early in the morning, pre-mountain bike ride, when I read that). 

I would say its either the jest version or the import order. Could you try putting the `import { RunWithDrivine } from "@liberation-data/drivine";` in the global setup?

**Comment by NilsMoller** [comment]
Just importing it does not work, but calling `RunWithDrivine` anywhere in the global setup does work, but this is not ideal.

**Comment by jasperblues** [comment]
And that's even if it is the first import in the global setup?

**Comment by NilsMoller** [comment]
Yes, I tried it as a first and later import, which does not work. In both scenarios I also tried it with actually calling the method, which does work.
