### ISSUE TITLE
How to enable an encrypted connection in the neo4j driver?

### ISSUE THREAD

**Issue by jogura** [liberation-data/drivine#80]
I'm working with a neo4j instance that requires TLS.  I couldn't find any documentation on how to pass in the encryption information to the neo4j driver from `drivine`.

When attempting to call the database without encryption the following error is returned:

> 2021-08-19T09:20:01.315-04:00]:[error] This server requires a TLS encrypted connection. {"ndc":"default","context":"ExceptionsHandler","stack":["Error: This server requires a TLS encrypted connection.\n    at Function.withRootCause (/Dev/node_modules/@liberation-data/src/DrivineError.ts:8:16)\n    at Transaction.query (/Dev/node_modules/@liberation-data/src/transaction/Transaction.ts:51:10)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at FinderOperations.maybeGetOne (/Dev/node_modules/@liberation-data/src/manager/FinderOperations.ts:16:25)\n    at TransactionalPersistenceManager.maybeGetOne (/Dev/node_modules/@liberation-data/src/manager/TransactionalPersistenceManager.ts:34:16)\n    at runInTransaction (/Dev/node_modules/@liberation-data/src/transaction/Transactional.ts:37:24)"]}

In the `Neo4jConnectionProvider`, current code:
```javascript
this.driver = neo.driver(`${this.protocol}://${this.host}:${this.port}`, authToken, {});
```

Modifying it to this seems to work (below is just an example):
```javascript
this.driver = neo.driver(`${this.protocol}://${this.host}:${this.port}`, authToken, {
  encrypted: 'ENCRYPTION_ON',
  trust: 'TRUST_ALL_CERTIFICATES'
});
```
Is there a better way to make the neo4j encryption configuration more configurable from the `drivine` side?

**Comment by jasperblues** [comment]
@jogura You were the first who has needed encryption. Sorry that you faced trouble. 

Would you like to create a pull request so that it is possible to set up encryption from: 

* Code based properties
* ENV properties 

If yes, I can merge it straight away, otherwise I can add support via an issue ticket as soon as free time allows.

**Comment by jogura** [comment]
A coworker of mine found this nugget in the [neo4j drivers documentation](https://neo4j.com/developer/javascript/#driver-configuration).

Certificate Type | Neo4j Causal Cluster | Neo4j Standalone Server | Direct Connection to Cluster Member
-- | -- | -- | --
Unencrypted | neo4j | neo4j | bolt
Encrypted with Full Certificate | neo4j+s | neo4j+s | bolt+s
Encrypted with Self-Signed Certificate | neo4j+ssc | neo4j+ssc | bolt+ssc
Neo4j Aura | neo4j+s | N/A | N/A

For our use case we just need to change the protocol from `bolt` to `bolt+ssc` and that solves our problem.

However, this will only work if you're using a neo4j driver 4.0 and onward.

Feel free to close this issue.

**Comment by jasperblues** [comment]
@jogura were you able to set this property via Drivine? Off the top of my head I can't recall if I provided that feature? 

If yes, great, otherwise we should add it.

**Comment by jogura** [comment]
@jasperblues yes you can set it in the configuration or programmatically as the documentation shows:

From the [quickstart guide](https://drivine.org/guide/#/quick-start):

Configuration style (using .env):
```
NEO_DATABASE_TYPE=NEO4J
NEO_DATABASE_USER='neo4j'
NEO_DATABASE_PASSWORD='h4ckM3'
NEO_DATABASE_HOST='localhost'
NEO_DATABASE_PORT='7687'
NEO_DATABASE_PROTOCOL='bolt+ssc'    <--- configure it here
```
or Programmatically:
```
@Module({
    imports: [
        DrivineModule.withOptions(<DrivineModuleOptions>{
            connectionProviders: [
                DatabaseRegistry.getInstance()
                    .builder()
                    .withProperties(ConnectionPropertiesFromEnv['NEO'])
                    .protocol('bolt+ssc') // <----- specify the protocol and schema here
                    .register('NEO')
            ]
        })
    ],
    providers: [RouteRepository],
    controllers: [RouteController]
})
```
